ALTER TABLE auth_session
    ADD COLUMN push_installation_id uuid,
    ADD COLUMN push_platform varchar(20),
    ADD COLUMN push_token_ciphertext text,
    ADD COLUMN push_token_lookup_hash char(64),
    ADD COLUMN push_last_seen_at timestamptz,
    ADD CONSTRAINT uk_auth_session_push_installation UNIQUE (push_installation_id),
    ADD CONSTRAINT uk_auth_session_push_token_lookup_hash UNIQUE (push_token_lookup_hash),
    ADD CONSTRAINT ck_auth_session_push_registration
        CHECK (
            (push_installation_id IS NULL AND push_platform IS NULL
                AND push_token_ciphertext IS NULL AND push_token_lookup_hash IS NULL
                AND push_last_seen_at IS NULL)
            OR
            (push_installation_id IS NOT NULL AND push_platform = 'ANDROID'
                AND push_token_ciphertext IS NOT NULL
                AND push_token_lookup_hash ~ '^[0-9a-f]{64}$'
                AND push_last_seen_at IS NOT NULL)
        );

CREATE TABLE chat_notification_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    message_id bigint NOT NULL,
    recipient_member_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until timestamptz,
    last_error_code varchar(50),
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    CONSTRAINT pk_chat_notification_outbox PRIMARY KEY (id),
    CONSTRAINT uk_chat_notification_outbox_message UNIQUE (message_id),
    CONSTRAINT fk_chat_notification_outbox_message
        FOREIGN KEY (message_id) REFERENCES chat_message (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_notification_outbox_recipient
        FOREIGN KEY (recipient_member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_notification_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'SKIPPED')),
    CONSTRAINT ck_chat_notification_outbox_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_chat_notification_outbox_completed_at
        CHECK ((status IN ('SENT', 'SKIPPED')) = (completed_at IS NOT NULL))
);

CREATE INDEX idx_auth_session_push_recipient
    ON auth_session (member_id, expires_at, id)
    WHERE revoked_at IS NULL AND push_installation_id IS NOT NULL;

CREATE INDEX idx_chat_notification_outbox_due
    ON chat_notification_outbox (next_attempt_at, lease_until, id)
    WHERE status IN ('PENDING', 'PROCESSING');
