CREATE TABLE member (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    login_id varchar(50) NOT NULL,
    password_hash varchar(255) NOT NULL,
    nickname varchar(30) NOT NULL,
    phone_ciphertext text,
    phone_lookup_hash char(64),
    phone_verified_at timestamptz,
    privacy_collection_policy_version varchar(50),
    privacy_collection_consented_at timestamptz,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE auth_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL,
    refresh_token_selector char(22) NOT NULL,
    refresh_token_hash char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL,
    last_used_at timestamptz,
    CONSTRAINT pk_auth_session PRIMARY KEY (id),
    CONSTRAINT uk_auth_session_refresh_token_selector UNIQUE (refresh_token_selector),
    CONSTRAINT uk_auth_session_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT fk_auth_session_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE TABLE animal_case (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    case_type varchar(20) NOT NULL,
    source_type varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    is_matchable boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    listed_at timestamptz NOT NULL,
    name varchar(50),
    species varchar(20) NOT NULL,
    breed_name varchar(100),
    sex varchar(20) NOT NULL,
    color varchar(100),
    event_date date NOT NULL,
    event_time time,
    feature_text text,
    closed_at timestamptz,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_animal_case PRIMARY KEY (id)
);

CREATE TABLE animal_case_location (
    animal_case_id bigint NOT NULL,
    location_type varchar(20) NOT NULL,
    region_code char(5) NOT NULL,
    emd_code char(10),
    public_location varchar(255) NOT NULL,
    exact_location_ciphertext text,
    exact_location_visible boolean NOT NULL DEFAULT false,
    disclosure_policy_version varchar(20),
    disclosure_consented_at timestamptz,
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    CONSTRAINT pk_animal_case_location PRIMARY KEY (animal_case_id, location_type),
    CONSTRAINT fk_animal_case_location_animal_case
        FOREIGN KEY (animal_case_id) REFERENCES animal_case (id) ON DELETE CASCADE
);

CREATE TABLE user_post (
    animal_case_id bigint NOT NULL,
    member_id bigint NOT NULL,
    client_request_id uuid NOT NULL,
    request_hash char(64) NOT NULL,
    close_reason varchar(30),
    CONSTRAINT pk_user_post PRIMARY KEY (animal_case_id),
    CONSTRAINT fk_user_post_animal_case
        FOREIGN KEY (animal_case_id) REFERENCES animal_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_post_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE RESTRICT
);

CREATE TABLE chat_room (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    animal_case_id bigint NOT NULL,
    owner_member_id bigint NOT NULL,
    requester_member_id bigint NOT NULL,
    last_message_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_chat_room PRIMARY KEY (id),
    CONSTRAINT uk_chat_room_case_requester UNIQUE (animal_case_id, requester_member_id),
    CONSTRAINT fk_chat_room_animal_case
        FOREIGN KEY (animal_case_id) REFERENCES animal_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_owner_member
        FOREIGN KEY (owner_member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_requester_member
        FOREIGN KEY (requester_member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE TABLE chat_message (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    chat_room_id bigint NOT NULL,
    sender_member_id bigint NOT NULL,
    client_message_id uuid NOT NULL,
    request_hash char(64) NOT NULL,
    content varchar(1000) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id),
    CONSTRAINT fk_chat_message_chat_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sender_member
        FOREIGN KEY (sender_member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE TABLE shelter (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    care_reg_no varchar(50) NOT NULL,
    name varchar(150) NOT NULL,
    phone varchar(50),
    address text,
    jurisdiction varchar(150),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_shelter PRIMARY KEY (id),
    CONSTRAINT uk_shelter_care_reg_no UNIQUE (care_reg_no)
);

CREATE TABLE ingestion_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source_system varchar(50) NOT NULL,
    run_type varchar(30) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'RUNNING',
    requested_from_date date,
    requested_to_date date,
    fetched_count integer NOT NULL DEFAULT 0,
    inserted_count integer NOT NULL DEFAULT 0,
    updated_count integer NOT NULL DEFAULT 0,
    shelter_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    last_source_updated_at timestamptz,
    error_summary text,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    summary_published_at timestamptz,
    CONSTRAINT pk_ingestion_run PRIMARY KEY (id)
);

CREATE TABLE shelter_animal (
    animal_case_id bigint NOT NULL,
    desertion_no varchar(50) NOT NULL,
    shelter_id bigint NOT NULL,
    ingestion_run_id bigint,
    notice_no varchar(100),
    notice_start_date date,
    notice_end_date date,
    process_state_raw varchar(100),
    end_reason_raw varchar(255),
    age_text varchar(100),
    weight_text varchar(100),
    neuter_status varchar(20) NOT NULL,
    source_updated_at timestamptz,
    last_synced_at timestamptz NOT NULL,
    CONSTRAINT pk_shelter_animal PRIMARY KEY (animal_case_id),
    CONSTRAINT uk_shelter_animal_desertion_no UNIQUE (desertion_no),
    CONSTRAINT fk_shelter_animal_animal_case
        FOREIGN KEY (animal_case_id) REFERENCES animal_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_shelter_animal_shelter
        FOREIGN KEY (shelter_id) REFERENCES shelter (id) ON DELETE RESTRICT,
    CONSTRAINT fk_shelter_animal_ingestion_run
        FOREIGN KEY (ingestion_run_id) REFERENCES ingestion_run (id) ON DELETE SET NULL
);

CREATE TABLE animal_photo (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    animal_case_id bigint NOT NULL,
    storage_type varchar(20) NOT NULL,
    storage_uri text NOT NULL,
    content_type varchar(50),
    byte_size bigint,
    width_px integer,
    height_px integer,
    sort_order smallint NOT NULL,
    checksum_sha256 char(64),
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_animal_photo PRIMARY KEY (id),
    CONSTRAINT uk_animal_photo_case_sort_order UNIQUE (animal_case_id, sort_order),
    CONSTRAINT fk_animal_photo_animal_case
        FOREIGN KEY (animal_case_id) REFERENCES animal_case (id) ON DELETE CASCADE
);

CREATE TABLE match_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    query_case_id bigint NOT NULL,
    query_case_version bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    model_id varchar(100) NOT NULL,
    model_version varchar(50) NOT NULL,
    candidate_count integer NOT NULL DEFAULT 0,
    error_code varchar(100),
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_match_run PRIMARY KEY (id),
    CONSTRAINT fk_match_run_animal_case
        FOREIGN KEY (query_case_id) REFERENCES animal_case (id) ON DELETE CASCADE
);

CREATE TABLE match_candidate (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_run_id bigint NOT NULL,
    target_case_id bigint NOT NULL,
    rank integer NOT NULL,
    total_score double precision NOT NULL,
    image_score double precision,
    distance_km double precision,
    time_gap_days integer,
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_match_candidate PRIMARY KEY (id),
    CONSTRAINT uk_match_candidate_run_target UNIQUE (match_run_id, target_case_id),
    CONSTRAINT uk_match_candidate_run_rank UNIQUE (match_run_id, rank),
    CONSTRAINT fk_match_candidate_match_run
        FOREIGN KEY (match_run_id) REFERENCES match_run (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_candidate_animal_case
        FOREIGN KEY (target_case_id) REFERENCES animal_case (id) ON DELETE CASCADE
);

ALTER TABLE member
    ADD CONSTRAINT ck_member_status
        CHECK (status IN ('ACTIVE', 'WITHDRAWN')),
    ADD CONSTRAINT ck_member_active_phone_policy
        CHECK (
            status <> 'ACTIVE'
            OR (
                phone_ciphertext IS NOT NULL
                AND phone_lookup_hash IS NOT NULL
                AND phone_verified_at IS NOT NULL
                AND privacy_collection_policy_version IS NOT NULL
                AND privacy_collection_consented_at IS NOT NULL
                AND deleted_at IS NULL
            )
        );

ALTER TABLE auth_session
    ADD CONSTRAINT ck_auth_session_expiry
        CHECK (expires_at > created_at),
    ADD CONSTRAINT ck_auth_session_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at);

ALTER TABLE animal_case
    ADD CONSTRAINT ck_animal_case_type
        CHECK (case_type IN ('LOST', 'SHELTERING')),
    ADD CONSTRAINT ck_animal_case_source
        CHECK (source_type IN ('USER', 'PUBLIC')),
    ADD CONSTRAINT ck_animal_case_source_type_pair
        CHECK (
            (source_type = 'USER')
            OR (source_type = 'PUBLIC' AND case_type = 'SHELTERING')
        ),
    ADD CONSTRAINT ck_animal_case_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'DELETED')),
    ADD CONSTRAINT ck_animal_case_status_dates
        CHECK (
            (status = 'ACTIVE' AND closed_at IS NULL AND deleted_at IS NULL)
            OR (status = 'CLOSED' AND closed_at IS NOT NULL AND deleted_at IS NULL)
            OR (status = 'DELETED' AND deleted_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_animal_case_species
        CHECK (species IN ('DOG', 'CAT', 'OTHER')),
    ADD CONSTRAINT ck_animal_case_sex
        CHECK (sex IN ('MALE', 'FEMALE', 'UNKNOWN')),
    ADD CONSTRAINT ck_animal_case_version
        CHECK (version >= 0);

ALTER TABLE animal_case_location
    ADD CONSTRAINT ck_animal_case_location_type
        CHECK (location_type IN ('EVENT', 'CURRENT')),
    ADD CONSTRAINT ck_animal_case_location_pair
        CHECK ((latitude IS NULL) = (longitude IS NULL)),
    ADD CONSTRAINT ck_animal_case_location_region_code
        CHECK (region_code ~ '^[0-9]{5}$'),
    ADD CONSTRAINT ck_animal_case_location_emd_code
        CHECK (emd_code IS NULL OR emd_code ~ '^[0-9]{10}$'),
    ADD CONSTRAINT ck_animal_case_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    ADD CONSTRAINT ck_animal_case_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    ADD CONSTRAINT ck_animal_case_location_disclosure
        CHECK (
            NOT exact_location_visible
            OR (
                exact_location_ciphertext IS NOT NULL
                AND disclosure_policy_version IS NOT NULL
                AND disclosure_consented_at IS NOT NULL
            )
        );

ALTER TABLE user_post
    ADD CONSTRAINT ck_user_post_request_hash
        CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    ADD CONSTRAINT ck_user_post_close_reason
        CHECK (close_reason IS NULL OR close_reason IN ('RETURNED', 'TRANSFERRED', 'OTHER'));

ALTER TABLE chat_room
    ADD CONSTRAINT ck_chat_room_participants
        CHECK (owner_member_id <> requester_member_id);

ALTER TABLE chat_message
    ADD CONSTRAINT ck_chat_message_content
        CHECK (char_length(btrim(content)) BETWEEN 1 AND 1000),
    ADD CONSTRAINT ck_chat_message_request_hash
        CHECK (request_hash ~ '^[0-9a-f]{64}$');

ALTER TABLE shelter_animal
    ADD CONSTRAINT ck_shelter_animal_notice_dates
        CHECK (
            notice_start_date IS NULL
            OR notice_end_date IS NULL
            OR notice_start_date <= notice_end_date
        ),
    ADD CONSTRAINT ck_shelter_animal_neuter_status
        CHECK (neuter_status IN ('YES', 'NO', 'UNKNOWN'));

ALTER TABLE animal_photo
    ADD CONSTRAINT ck_animal_photo_storage_type
        CHECK (storage_type IN ('USER_UPLOAD', 'PUBLIC_URL')),
    ADD CONSTRAINT ck_animal_photo_sort_order
        CHECK (sort_order BETWEEN 0 AND 9),
    ADD CONSTRAINT ck_animal_photo_user_metadata
        CHECK (
            storage_type <> 'USER_UPLOAD'
            OR (
                storage_uri ~ '^/data/user/images/[1-9][0-9]*/[1-9][0-9]*[.]jpg$'
                AND content_type IS NOT NULL AND content_type = 'image/jpeg'
                AND byte_size IS NOT NULL AND byte_size > 0
                AND width_px IS NOT NULL AND width_px BETWEEN 1 AND 4096
                AND height_px IS NOT NULL AND height_px BETWEEN 1 AND 4096
                AND checksum_sha256 IS NOT NULL AND checksum_sha256 ~ '^[0-9a-f]{64}$'
            )
        );

ALTER TABLE match_run
    ADD CONSTRAINT ck_match_run_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    ADD CONSTRAINT ck_match_run_candidate_count
        CHECK (candidate_count BETWEEN 0 AND 20),
    ADD CONSTRAINT ck_match_run_timestamps
        CHECK (
            (status = 'PENDING' AND completed_at IS NULL)
            OR (status = 'RUNNING' AND started_at IS NOT NULL AND completed_at IS NULL)
            OR (status IN ('SUCCEEDED', 'FAILED')
                AND started_at IS NOT NULL AND completed_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_match_run_error
        CHECK (
            (status = 'FAILED' AND error_code IS NOT NULL)
            OR (status <> 'FAILED' AND error_code IS NULL)
        );

ALTER TABLE match_candidate
    ADD CONSTRAINT ck_match_candidate_rank
        CHECK (rank BETWEEN 1 AND 20),
    ADD CONSTRAINT ck_match_candidate_total_score
        CHECK (total_score BETWEEN 0 AND 1),
    ADD CONSTRAINT ck_match_candidate_image_score
        CHECK (image_score IS NULL OR image_score BETWEEN 0 AND 1),
    ADD CONSTRAINT ck_match_candidate_distance
        CHECK (distance_km IS NULL OR distance_km >= 0),
    ADD CONSTRAINT ck_match_candidate_time_gap
        CHECK (time_gap_days IS NULL OR time_gap_days >= 0);

ALTER TABLE ingestion_run
    ADD CONSTRAINT ck_ingestion_run_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    ADD CONSTRAINT ck_ingestion_run_type
        CHECK (run_type IN ('INITIAL_FULL', 'DAILY_INCREMENTAL', 'BACKFILL')),
    ADD CONSTRAINT ck_ingestion_run_counts
        CHECK (
            fetched_count >= 0 AND inserted_count >= 0
            AND updated_count >= 0 AND shelter_count >= 0 AND failed_count >= 0
        ),
    ADD CONSTRAINT ck_ingestion_run_request_dates
        CHECK (
            requested_from_date IS NULL
            OR requested_to_date IS NULL
            OR requested_from_date <= requested_to_date
        ),
    ADD CONSTRAINT ck_ingestion_run_completed_at
        CHECK (
            (status = 'RUNNING' AND completed_at IS NULL)
            OR (status IN ('SUCCEEDED', 'FAILED') AND completed_at IS NOT NULL)
        );

CREATE INDEX idx_animal_case_list
    ON animal_case (case_type, listed_at DESC, id DESC)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_animal_case_list_filter
    ON animal_case (case_type, species, sex, listed_at DESC, id DESC)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_animal_case_location_public
    ON animal_case_location (location_type, region_code, animal_case_id);

CREATE UNIQUE INDEX idx_member_login_id_canonical
    ON member (login_id);

CREATE UNIQUE INDEX idx_member_active_phone_lookup_hash
    ON member (phone_lookup_hash)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_auth_session_member_active
    ON auth_session (member_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_user_post_member
    ON user_post (member_id, animal_case_id);

CREATE UNIQUE INDEX uk_user_post_member_client_request
    ON user_post (member_id, client_request_id);

CREATE INDEX idx_chat_room_owner_latest
    ON chat_room (owner_member_id, updated_at DESC, id DESC);

CREATE INDEX idx_chat_room_requester_latest
    ON chat_room (requester_member_id, updated_at DESC, id DESC);

CREATE INDEX idx_chat_message_room_cursor
    ON chat_message (chat_room_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX uk_chat_message_sender_client_message
    ON chat_message (sender_member_id, client_message_id);

CREATE INDEX idx_animal_case_matchable
    ON animal_case (case_type, listed_at DESC, id DESC)
    WHERE is_matchable = true;

CREATE INDEX idx_shelter_animal_shelter
    ON shelter_animal (shelter_id, animal_case_id);

CREATE INDEX idx_match_run_latest_success
    ON match_run (query_case_id, completed_at DESC, id DESC)
    WHERE status = 'SUCCEEDED';

CREATE UNIQUE INDEX idx_match_run_active_query
    ON match_run (query_case_id)
    WHERE status IN ('PENDING', 'RUNNING');

CREATE INDEX idx_match_candidate_run_rank
    ON match_candidate (match_run_id, rank);

CREATE INDEX idx_match_candidate_target
    ON match_candidate (target_case_id);

CREATE INDEX idx_ingestion_run_latest_success
    ON ingestion_run (source_system, completed_at DESC)
    WHERE status = 'SUCCEEDED';
