CREATE TABLE member_photo_erasure_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    storage_uri text NOT NULL,
    deadline_at timestamptz NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL,
    lease_until timestamptz,
    last_error_code varchar(30),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_member_photo_erasure_task PRIMARY KEY (id),
    CONSTRAINT uk_member_photo_erasure_task_storage_uri UNIQUE (storage_uri),
    CONSTRAINT ck_member_photo_erasure_task_path
        CHECK (storage_uri ~ '^/data/user/images/[1-9][0-9]{0,18}/[1-9][0-9]{0,18}\.jpg$'),
    CONSTRAINT ck_member_photo_erasure_task_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_member_photo_erasure_task_error
        CHECK (last_error_code IS NULL OR last_error_code = 'PHOTO-006'),
    CONSTRAINT ck_member_photo_erasure_task_timestamps
        CHECK (
            next_attempt_at >= created_at
            AND updated_at >= created_at
            AND (lease_until IS NULL OR lease_until >= updated_at)
        )
);

CREATE INDEX idx_member_photo_erasure_task_due
    ON member_photo_erasure_task (next_attempt_at, lease_until, id);
